apiVersion: skaffold/v1beta13
kind: Config
build: 
  local:
    push: false
  artifacts:
    - image: sainthkh/store-admin
      context: .
      docker:
        dockerfile: admin.dev.Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
          - src: '**/*.ts'
            dest: .
          - src: '**/*.css'
            dest: .
          - src: '**/*.html'
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/admin-deployment.yaml