apiVersion: v1
kind: Service
metadata:
  name: admin-cluster-ip-service
spec:
  type: NodePort
  selector:
    app: admin
    tier: frontend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31000