apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-gateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      component: gateway
  template:
    metadata:
      labels:
        component: gateway
    spec:
      containers:
        - name: gateway-server
          image: sainthkh/store-gateway
          ports:
            - containerPort: 4000
